### ISSUE TITLE
Bold content is not transformed properly

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#107]
For example on https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/ask-alan-shipnuck-brian-harman-disrespect-rory-mcilroy-conundrum-overrated-british-fans-ryder-cup-picks-liv-golf-next-move,  there is content that starts with ** and ends with ** which should be bold actually. 

@hsaginor In theory we could transform it client-side but it should be ideally fixed as part of the importer wdyt ?. 

<img width="1407" alt="Screenshot 2023-08-07 at 15 48 39" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/1854d3e7-98fc-4a11-8fc4-93c5b5f954e5">

**Comment by hsaginor** [comment]
@icaraps I agree that the importer should handle it. Our import.js script is actual scraping all this content as IS.

Here is the markup we are scraping in this case
`<p style="background-image: none;"><b style="background-image: none;">Is it a “thing” in Rory’s head at this point?<span style="background-image: none;"> </span></b><a href="https://twitter.com/TheNo1OGGolfer" target="_blank" rel="noopener noreferrer" style="background-image: none;"><b style="background-image: none;">@TheNo1OGGolfer</b></a></p>`

It's translated to this markdown:
`**Is it a “thing” in Rory’s head at this point? **`

So it looks like the problem is the extra blank space in the original markup `<span style="background-image: none;"> </span>`. I can probably try to look for these and remove extra spaces in the import script but it could be hard to catch all the "weird" cases like this. It looks like all this content is authored in RTE in AEM. So, it could be anything.

**Comment by icaraps** [comment]
> So it looks like the problem is the extra blank space in the original markup

@hsaginor ok I've seen it in many imported documents so it's probably worth fixing.

**Comment by icaraps** [comment]
Also it would make sense to test it on a smaller set of documents eg only 2023 articles in the beginning to iterate faster.
