### ISSUE TITLE
Longform brightcove video ids are not imported 

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#135]
For example on https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/6/rocket-mortgage-classic-dfs-picks-2023, the ?videoId  is null

**Comment by hsaginor** [comment]
@icaraps Based on the original content sometimes it's going to be a playlistId instead of videoId. So, the link will be https://players.brightcove.net/6181004287001/lK20vBz8j_default/index.html?playlistId=1685002491667503732

I am fixing the importer but the site should be fixed to handle this as well. 

Also, we should implement it using Brightcove JS API similar to the original site. There was a ticket but it got shelved since it wasn't a priority (maybe still is not).

**Comment by hsaginor** [comment]
@icaraps Here is the reimported document with playlistId

**Comment by hsaginor** [comment]
Fixed and reimported document -
https://docs.google.com/document/d/1eFcTtG-cxoeVFHR7Fdso1khTU-TvJCbxW6-oQOISUUo/edit
https://main--helix-sportsmagazine--headwirecom.hlx.live/content-v2/the-loop/gambling/article/2023/6/rocket-mortgage-classic-dfs-picks-2023

Full reimport will be needed to fix on all pages
