### ISSUE TITLE
og:image is not always imported 

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#204]
@hsaginor On https://main--helix-sportsmagazine--headwirecom.hlx.page and other landing pages which are using the article index to retrieve and display content, you'll notice that some images are missing. 

I found out that the og:image value is wrong e.g. for article https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/wesley-bryan-emerges-from-pga-tour-monday-qualifier-playoff-that-includes-older-brother it corresponds to `https://main--helix-sportsmagazine--headwirecom.hlx.page/default-meta-image.png?width=1200&#x26;format=pjpg&#x26;optimize=medium` instead of `https://golfdigest.sports.sndimg.com/content/dam/images/golfdigest/fullset/2021/230731-bryan-brothers.png.rend.hgtvcom.616.616.suffix/1690832716954.png` from https://www.golfdigest.com/story/wesley-bryan-emerges-from-pga-tour-monday-qualifier-playoff-that-includes-older-brother

**Comment by hsaginor** [comment]
@icaraps Importing the image in metadata block seems to work.

Here is a test document 
https://docs.google.com/document/d/1fH9pZaRVoVsELVWtgN0EN8bwPMyUvF_NISjDAfBGPVQ/edit
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/wesley-bryan-emerges-from-pga-tour-monday-qualifier-playoff-that-includes-older-brother-2

We should probably also add a "default" image to the project since Franklin always adds it to the page even if it's not in the metadata block.
 
I will merge importer changes tomorrow. There are a lot of fixes

**Comment by icaraps** [comment]
Yup it's working great thx ! 👍
