### ISSUE TITLE
Some section breaks are not imported

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#258]
section breaks created using CSS are not imported in any way.

(at the bottom of this page)
https://www.golfdigest.com/story/british-open-2023-top-100-players-in-the-field-at-royal-liverpool-hoylake-ranked

google doc:
https://docs.google.com/document/d/1fYLCNVBZiha22N05MFkV20F2oi3IyHOFhe5Zm7ES0pE/edit

**Comment by hsaginor** [comment]
@DriftingSands I looked into this. I am assuming you are referring to the div with the "sectionBreak" class at the bottom (the 3 dots). The import script doesn't really do anything special with this markup. It just scrapes it from the original page. But style classes are not generally representable in the Markdown and word docs the importer outputs. So, as with everything else, I would need to know how do you want this represented in google document so that the importer can handle it explicitly.

BTW this comment would apply to anything you want imported to a Franklin Google Document. Style classes are not carried over unless we define an explicit block. And section breaks are represented with horizontal lines.

cc: @icaraps

**Comment by hsaginor** [comment]
Closing for now as this can't be handled by the importer until it's defined how this should be represented in the the imported document. cc: @icaraps @DriftingSands
